#!/usr/bin/env bash
# script print "Best School" 10 times and "Hi" during the nine time
i=1
while [ "$i" -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]; then
	echo "Hi"
    fi
    (( i++ ))
done
