#!/usr/bin/env bash
#it says "Best School" 10x, "bad luck" at  four time, "good luck" at eight time

i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]; then
	echo "bad luck"
    elif [ "$i" -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
