#!/usr/bin/env bash
# "bad luck from China" at four time,
# "bad luck from Japan" at  nine time, and "bad luck from Italy" at the seventeen time.

i=1
while [ "$i" -le 20 ]
do
    echo "$i"
    case $i in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( i++ ))
done
